<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Ramya" ignored="0" name="Test Assertions" tests="2" failures="1" timestamp="06 Mar 2018 14:16:15 GMT" time="53.879" errors="0">
  <testcase name="getTitle" time="0.027" classname="testNG.TestNGAssertions"/>
  <testcase name="testEquality" time="0.003" classname="testNG.TestNGAssertions">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testNG.TestNGAssertions.testEquality(TestNGAssertions.java:34)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testEquality -->
</testsuite> <!-- Test Assertions -->
